### ISSUE TITLE
No aarch64-osx jar on central

### ISSUE THREAD

**Issue by Fristi** [indoorvivants/sn-bindgen#142]
In the release there is a download for arm64 https://github.com/indoorvivants/sn-bindgen/releases/tag/v0.0.14

But it's not been published to central it seems?

```
[error] stack trace is suppressed; run last bindgenBinary for the full output
[error] (bindgenBinary) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/com/indoorvivants/bindgen_native0.4_3/0.0.14/bindgen_native0.4_3-0.0.14-aarch_64-osx.jar: not found: https://repo1.maven.org/maven2/com/indoorvivants/bindgen_native0.4_3/0.0.14/bindgen_native0.4_3-0.0.14-aarch_64-osx.jar
```

**Comment by keynmol** [comment]
Hello!

> In the release there is a download for arm64 https://github.com/indoorvivants/sn-bindgen/releases/tag/v0.0.14

Yes, this is "cleanly" built on my M1 machine and uploaded manually.

Because currently, Github doesn't have M1 runners available, I cannot build and publish arm64 osx version from CI unfortunately. 

So there are two options:

1. As README says (probably need to put it on the website) you can checkout the 0.0.14 tag and publish locally 

![image](https://user-images.githubusercontent.com/1052965/208375161-5f3da85e-59cf-4a0e-9c0c-aa5ef62f479b.png)

2. You can use the binary directly (won't work obviously if you pulled a project with SBT configuration, like sn-bindgen-examples or something)

Figuring out how to publish just the arm64 jar from my local is on my TODO list :)

**Comment by Fristi** [comment]
Thank you for the quick reply ;) That worked.

An option for M1 maybe would be docker buildx
